"""
Clinical Notes Generator

Generates realistic unstructured clinical narratives from the existing
structured monitoring data.  Each patient gets a single JSON file
containing free-text clinician notes, lab reports, and imaging
narratives — simulating what a real clinical site would have *before*
any NLP/structuring step.

Usage::

    python -m data.monitoring.generate_clinical_notes

Pre-requisite:
    Structured JSON must already exist (generated by generate_monitoring_data.py).
"""

from __future__ import annotations

import json
import random
from datetime import datetime
from pathlib import Path
from typing import Any

_OUTPUT_DIR = Path(__file__).resolve().parent

# Re-seed for reproducibility but different from main generator
random.seed(99)

# ── Narrative templates ──

_GREETING_TEMPLATES = [
    "Patient {pid} presents for scheduled cycle {visit} visit.",
    "{pid} — Cycle {visit}, Day 1 visit.",
    "Follow-up visit #{visit} for patient {pid}.",
    "Routine protocol visit {visit}. Patient ID: {pid}.",
    "Visit {visit} clinical encounter for {pid}.",
]

_VITALS_TEMPLATES = [
    "Vitals: BP {sbp}/{dbp} mmHg, HR {hr} bpm, Weight {wt} kg.",
    "Vital signs obtained: blood pressure {sbp}/{dbp}, heart rate {hr}, weight {wt} kg.",
    "On exam, BP is {sbp}/{dbp}, pulse {hr}, wt {wt} kg. Patient appears {appearance}.",
    "VS: {sbp}/{dbp} | HR {hr} | Wt {wt} kg. {appearance_note}",
]

_APPEARANCE_PHRASES = [
    "well-nourished and in no acute distress",
    "mildly fatigued but alert and oriented",
    "comfortable, no distress noted",
    "slightly pale but hemodynamically stable",
    "well-appearing, cooperative with exam",
]

_AE_NARRATIVE_TEMPLATES = {
    "Nausea": [
        "Patient reports {severity} nausea since last visit, onset approximately day {onset}. {resolution_text} {action_text}",
        "Experiencing {severity} nausea (CTCAE Grade {grade}) beginning around day {onset} of current cycle. {resolution_text} {action_text}",
        "Complains of {severity} nausea. Started day {onset}. {resolution_text} Assessed as {relatedness} to study drug. {action_text}",
    ],
    "Fatigue": [
        "Reports {severity} fatigue ({grade_text}) since approximately day {onset}. {resolution_text} {action_text}",
        "Ongoing {severity} fatigue noted. Patient states it began around day {onset} and {resolution_text_lower} {action_text}",
        "Significant tiredness reported — classified as Grade {grade} fatigue. Onset day {onset}. {resolution_text} {action_text}",
    ],
    "Anemia": [
        "Lab-confirmed anemia — Hemoglobin trending down. Grade {grade} per CTCAE. Onset day {onset}. {resolution_text} {action_text}",
        "Patient noted to have {severity} anemia (Grade {grade}) on routine labs, first detected day {onset}. {resolution_text} {action_text}",
    ],
    "Neutropenia": [
        "ANC decreased — Grade {grade} neutropenia identified on day {onset} labs. {resolution_text} {action_text}",
        "{severity} neutropenia detected. CTCAE Grade {grade}, onset day {onset}. {resolution_text} Patient monitored closely. {action_text}",
    ],
    "Diarrhea": [
        "Patient reports {severity} diarrhea beginning day {onset}. {resolution_text} {action_text}",
        "New onset diarrhea, Grade {grade}, started day {onset}. {resolution_text} Hydration encouraged. {action_text}",
    ],
    "Hepatotoxicity": [
        "Liver enzymes elevated — classified as Grade {grade} hepatotoxicity. Detected on day {onset} labs. {resolution_text} {action_text}",
        "ALT/AST elevation consistent with {severity} hepatotoxicity (Grade {grade}). Onset day {onset}. {resolution_text} {action_text}",
    ],
    "Peripheral neuropathy": [
        "Patient reports tingling/numbness in extremities — {severity} peripheral neuropathy, Grade {grade}. Onset day {onset}. {resolution_text} {action_text}",
        "Neuropathic symptoms noted: {severity} (Grade {grade}). Patient describes onset around day {onset}. {resolution_text} {action_text}",
    ],
}

_AE_GENERIC_TEMPLATES = [
    "Adverse event noted: {ae_term} — {severity} (CTCAE Grade {grade}). Onset day {onset}. {resolution_text} Assessed as {relatedness} to study drug. {action_text}",
    "Patient reports {ae_term} ({severity}, Grade {grade}). First noted day {onset}. {resolution_text} {action_text}",
    "New AE: {ae_term}. Severity: {severity} (Grade {grade}). Onset: day {onset}. {resolution_text} Relatedness: {relatedness}. {action_text}",
]

_LAB_INTRO_TEMPLATES = [
    "Laboratory results:",
    "Labs drawn today:",
    "Routine labs obtained:",
    "Lab panel results from today's draw:",
    "Blood work results:",
]

_IMAGING_TEMPLATES = {
    "CR": [
        "Imaging assessment (CT chest/abdomen/pelvis): Complete response — no measurable disease identified. All previously noted target lesions have resolved. Classified as CR per RECIST 1.1.",
        "Restaging CT demonstrates complete disappearance of all target lesions. No new lesions. RECIST assessment: Complete Response (CR).",
    ],
    "PR": [
        "Imaging assessment: Target lesion decreased from baseline — measured reduction of approximately {change_pct}%. Partial response per RECIST 1.1 criteria.",
        "CT restaging shows partial response. Target lesions reduced significantly ({change_pct}% decrease from baseline). No new lesions identified. RECIST: PR.",
        "Imaging reveals meaningful tumor shrinkage consistent with partial response (PR). Target lesion regression of ~{change_pct}%.",
    ],
    "SD": [
        "Imaging: Target lesion measurements stable — neither sufficient shrinkage for PR nor increase for PD. Classified as stable disease (SD) per RECIST.",
        "Restaging CT shows stable disease. Target lesions within +/-15% of prior measurements. No new lesions. RECIST: SD.",
    ],
    "PD": [
        "Imaging assessment: Target lesion has increased by approximately {change_pct}% from nadir. Progressive disease (PD) per RECIST 1.1.",
        "CT shows disease progression — new lesion identified in the liver. Target measurements also increased ({change_pct}%). RECIST classification: PD.",
        "Concerning findings on restaging: tumor growth of {change_pct}%. Progressive disease per RECIST criteria.",
    ],
}

_BIOMARKER_TEMPLATES = [
    "PSA level is {value} ng/mL ({change_direction} {abs_change_pct}% from baseline).",
    "Serum PSA: {value} ng/mL, representing a {change_direction} of {abs_change_pct}% compared to baseline.",
    "PSA now {value} ng/mL — {change_direction} {abs_change_pct}% from initial value.",
]

_MISSED_VISIT_TEMPLATES = [
    "Patient did not present for scheduled visit {visit}. Attempted phone contact — {contact_outcome}.",
    "Visit {visit} — MISSED. Patient called to reschedule but did not attend. {contact_outcome}.",
    "No-show for cycle {visit} visit. Staff attempted follow-up: {contact_outcome}.",
    "Scheduled visit {visit} was not completed. {contact_outcome}.",
]

_CONTACT_OUTCOMES = [
    "no answer",
    "voicemail left",
    "spoke with patient, rescheduling",
    "patient's family member confirmed patient was unwell",
    "unable to reach patient",
    "patient reported feeling too unwell to travel to site",
]

_DROPOUT_NARRATIVE_TEMPLATES = {
    "adverse_event": "Patient discontinued from study due to intolerable adverse events. Treatment-related toxicity exceeded acceptable threshold per investigator judgment.",
    "disease_progression": "Patient removed from study protocol following confirmed disease progression on latest imaging. Referred to alternate treatment pathway.",
    "patient_withdrawal": "Patient elected to withdraw consent and discontinue participation in the trial. Reason cited: personal/family considerations.",
    "protocol_violation": "Subject discontinued due to significant protocol deviation identified during monitoring visit.",
    "lost_to_follow_up": "Patient lost to follow-up. Multiple contact attempts have been unsuccessful over the past 4 weeks.",
    "physician_decision": "Investigator decision to discontinue patient from study in best interest of patient care.",
}

_ACTION_TEXT_MAP = {
    "none": "No dose modification required.",
    "dose_reduced": "Study drug dose was reduced per protocol guidelines.",
    "dose_interrupted": "Treatment was held pending resolution. Dose interruption documented.",
    "discontinued": "Study drug was permanently discontinued due to this event.",
}

_PLAN_TEMPLATES = [
    "Plan: Continue current regimen. Follow up in {interval} weeks.",
    "Assessment: Tolerating therapy. Plan to continue protocol. Next visit in {interval} weeks.",
    "Plan: {plan_detail}. Return for cycle {next_visit} in {interval} weeks.",
    "Continue study protocol. Monitor labs. Return visit {next_visit} scheduled in {interval} weeks.",
]

_PLAN_DETAILS = [
    "Continue current dose",
    "Supportive care as needed",
    "Monitor closely and reassess at next visit",
    "Continue therapy per protocol with supportive medications",
]


def _resolution_text(outcome: str, resolution_day: int | None) -> tuple[str, str]:
    """Return (sentence-case, lower-case) resolution text."""
    if outcome == "resolved" and resolution_day:
        s = f"Resolved by day {resolution_day}."
        return s, f"resolved by day {resolution_day}."
    elif outcome == "ongoing":
        return "Currently ongoing.", "is currently ongoing."
    elif outcome == "resolved_with_sequelae" and resolution_day:
        s = f"Resolved with sequelae by day {resolution_day}."
        return s, f"resolved with sequelae by day {resolution_day}."
    else:
        return "Status documented.", "status documented."


def _grade_to_text(grade: int) -> str:
    """Informal grade description."""
    return {1: "Grade 1", 2: "Grade 2", 3: "Grade 3", 4: "Grade 4", 5: "Grade 5 (fatal)"}.get(grade, f"Grade {grade}")


def _build_visit_narrative(
    patient_id: str,
    visit: dict,
    aes_this_visit: list[dict],
    labs_this_visit: list[dict],
    response_this_visit: dict | None,
) -> str:
    """Build a single visit clinical note from structured data."""
    lines: list[str] = []
    visit_num = visit["visit_number"]
    visit_date = visit["visit_date"]
    status = visit["status"]

    lines.append(f"--- Visit {visit_num} | Date: {visit_date} ---")
    lines.append("")

    if status == "missed":
        template = random.choice(_MISSED_VISIT_TEMPLATES)
        contact = random.choice(_CONTACT_OUTCOMES)
        lines.append(template.format(visit=visit_num, contact_outcome=contact))

        # If this is a dropout visit, add the dropout narrative
        if visit.get("dropout_reason"):
            reason = visit["dropout_reason"]
            lines.append("")
            lines.append(
                _DROPOUT_NARRATIVE_TEMPLATES.get(
                    reason,
                    f"Patient discontinued. Reason: {reason}.",
                )
            )
        lines.append("")
        return "\n".join(lines)

    # Completed visit — greeting
    greeting = random.choice(_GREETING_TEMPLATES).format(pid=patient_id, visit=visit_num)
    lines.append(greeting)
    lines.append("")

    # Vitals
    vitals = visit.get("vitals")
    if vitals:
        appearance = random.choice(_APPEARANCE_PHRASES)
        tmpl = random.choice(_VITALS_TEMPLATES)
        lines.append(tmpl.format(
            sbp=vitals.get("blood_pressure_systolic", 120),
            dbp=vitals.get("blood_pressure_diastolic", 80),
            hr=vitals.get("heart_rate", 72),
            wt=vitals.get("weight_kg", 75),
            appearance=appearance,
            appearance_note=f"Patient {appearance}.",
        ))
        lines.append("")

    # Adverse events mentioned in this visit
    if aes_this_visit:
        for ae in aes_this_visit:
            ae_term = ae["ae_term"]
            severity = ae["severity"]
            grade = ae["grade"]
            onset = ae["onset_day"]
            relatedness = ae.get("relatedness", "possible")
            action = ae.get("action_taken", "none")
            outcome = ae.get("outcome", "ongoing")
            resolution_day = ae.get("resolution_day")

            res_text, res_text_lower = _resolution_text(outcome, resolution_day)
            action_text = _ACTION_TEXT_MAP.get(action, "")

            # Pick template
            specific_templates = _AE_NARRATIVE_TEMPLATES.get(ae_term)
            if specific_templates:
                tmpl = random.choice(specific_templates)
            else:
                tmpl = random.choice(_AE_GENERIC_TEMPLATES)

            note = tmpl.format(
                ae_term=ae_term,
                severity=severity,
                grade=grade,
                grade_text=_grade_to_text(grade),
                onset=onset,
                relatedness=relatedness,
                resolution_text=res_text,
                resolution_text_lower=res_text_lower,
                action_text=action_text,
            )
            lines.append(note)
        lines.append("")
    else:
        if random.random() < 0.5:
            lines.append("No new adverse events reported since last visit.")
            lines.append("")

    # Lab results
    if labs_this_visit:
        lines.append(random.choice(_LAB_INTRO_TEMPLATES))
        for lab in labs_this_visit:
            name = lab["lab_name"]
            value = lab["lab_value"]
            unit = lab["lab_unit"]
            ref_low = lab.get("reference_low", 0)
            ref_high = lab.get("reference_high", 100)

            flag = ""
            if value < ref_low:
                flag = " (LOW)"
            elif value > ref_high:
                flag = " (HIGH)"

            lines.append(f"  - {name}: {value} {unit} [ref {ref_low}-{ref_high}]{flag}")
        lines.append("")

    # Imaging / treatment response (if assessment visit)
    if response_this_visit:
        category = response_this_visit["response_category"]
        psa_val = response_this_visit.get("biomarker_value", 0)
        psa_change = response_this_visit.get("biomarker_change_pct", 0)

        tmpl_list = _IMAGING_TEMPLATES.get(category, _IMAGING_TEMPLATES["SD"])
        tmpl = random.choice(tmpl_list)
        abs_change = abs(round(psa_change, 1))
        lines.append(tmpl.format(change_pct=abs_change))
        lines.append("")

        # Biomarker
        change_dir = "decrease" if psa_change < 0 else "increase"
        bio_tmpl = random.choice(_BIOMARKER_TEMPLATES)
        lines.append(bio_tmpl.format(
            value=psa_val,
            change_direction=change_dir,
            abs_change_pct=abs_change,
        ))
        lines.append("")

    # Plan
    interval = 3  # 3-week visits
    next_visit = visit_num + 1
    plan = random.choice(_PLAN_TEMPLATES).format(
        interval=interval,
        next_visit=next_visit,
        plan_detail=random.choice(_PLAN_DETAILS),
    )
    lines.append(plan)
    lines.append("")

    return "\n".join(lines)


def generate_patient_notes(
    patient_id: str,
    visits: list[dict],
    adverse_events: list[dict],
    lab_results: list[dict],
    responses: list[dict],
) -> dict[str, Any]:
    """Generate a clinical notes document for one patient."""
    # Sort visits by visit number
    visits_sorted = sorted(visits, key=lambda v: v.get("visit_number", 0))

    # Index AEs by approximate visit (onset_day / 21 → visit number)
    ae_by_visit: dict[int, list[dict]] = {}
    for ae in adverse_events:
        # Assign AE to the visit closest to its onset
        onset_day = ae.get("onset_day", 1)
        approx_visit = max(1, (onset_day - 1) // 21 + 1)
        ae_by_visit.setdefault(approx_visit, []).append(ae)

    # Index labs by visit
    labs_by_visit: dict[int, list[dict]] = {}
    for lab in lab_results:
        v = lab.get("visit_number", 0)
        labs_by_visit.setdefault(v, []).append(lab)

    # Index responses by visit
    resp_by_visit: dict[int, dict] = {}
    for r in responses:
        v = r.get("assessment_visit", 0)
        resp_by_visit[v] = r

    documents: list[dict[str, Any]] = []

    for visit in visits_sorted:
        vnum = visit["visit_number"]
        vdate = visit["visit_date"]
        status = visit["status"]

        aes_for_visit = ae_by_visit.get(vnum, [])
        labs_for_visit = labs_by_visit.get(vnum, [])
        resp_for_visit = resp_by_visit.get(vnum)

        narrative = _build_visit_narrative(
            patient_id, visit, aes_for_visit, labs_for_visit, resp_for_visit
        )

        doc_type = "progress_note"
        if status == "missed":
            doc_type = "missed_visit_note"
        elif resp_for_visit:
            doc_type = "progress_note_with_imaging"

        documents.append({
            "visit_number": vnum,
            "date": vdate,
            "type": doc_type,
            "text": narrative,
        })

    return {
        "patient_id": patient_id,
        "documents": documents,
    }


def generate_site_clinical_notes(site_id: str) -> list[dict[str, Any]]:
    """Generate clinical notes for all patients at a site.

    Reads the existing structured JSON and converts each patient's
    data into unstructured clinical narratives.
    """
    site_dir = _OUTPUT_DIR / site_id
    if not site_dir.exists():
        print(f"  Warning: {site_dir} does not exist. Run generate_monitoring_data.py first.")
        return []

    # Load structured data
    def _load(name: str) -> list[dict]:
        p = site_dir / f"{name}.json"
        if p.exists():
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)
        return []

    visits = _load("visits")
    aes = _load("adverse_events")
    labs = _load("lab_results")
    responses = _load("responses")

    # Group by patient
    patients: dict[str, dict[str, list]] = {}
    for v in visits:
        pid = v["patient_id"]
        patients.setdefault(pid, {"visits": [], "aes": [], "labs": [], "responses": []})
        patients[pid]["visits"].append(v)
    for ae in aes:
        pid = ae["patient_id"]
        patients.setdefault(pid, {"visits": [], "aes": [], "labs": [], "responses": []})
        patients[pid]["aes"].append(ae)
    for lab in labs:
        pid = lab["patient_id"]
        patients.setdefault(pid, {"visits": [], "aes": [], "labs": [], "responses": []})
        patients[pid]["labs"].append(lab)
    for r in responses:
        pid = r["patient_id"]
        patients.setdefault(pid, {"visits": [], "aes": [], "labs": [], "responses": []})
        patients[pid]["responses"].append(r)

    all_notes: list[dict[str, Any]] = []
    for pid in sorted(patients.keys()):
        pdata = patients[pid]
        notes = generate_patient_notes(
            pid,
            pdata["visits"],
            pdata["aes"],
            pdata["labs"],
            pdata["responses"],
        )
        all_notes.append(notes)

    return all_notes


def main() -> None:
    """Generate clinical notes for all sites."""
    for site_id in ["site_a", "site_b"]:
        print(f"Generating clinical notes for {site_id}...")

        notes = generate_site_clinical_notes(site_id)

        # Write per-patient files
        notes_dir = _OUTPUT_DIR / site_id / "clinical_notes"
        notes_dir.mkdir(parents=True, exist_ok=True)

        for patient_note in notes:
            pid = patient_note["patient_id"]
            filepath = notes_dir / f"{pid}.json"
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(patient_note, f, indent=2)
            num_docs = len(patient_note["documents"])
            print(f"  {pid}: {num_docs} visit notes -> {filepath.name}")

        print(f"  Total: {len(notes)} patients")
        print()

    print("Done!")


if __name__ == "__main__":
    main()
